name: Update PR Title

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  update_pr_title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Update PR Title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          const github = require('@actions/github');
          const core = require('@actions/core');

          async function updatePRTitle() {
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            const { context } = github;
            
            const pr_number = context.payload.pull_request.number;
            const base_branch = context.payload.pull_request.base.ref;
            
            if (base_branch.startsWith('dev/')) {
              const branch_code = base_branch.split('/').pop();
              const original_title = context.payload.pull_request.title;
              const new_title = `[${branch_code}] ${original_title}`;

              if (original_title !== new_title) {
                const { data } = await octokit.rest.pulls.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr_number,
                  title: new_title
                });

                console.log(`PR title updated to "${data.title}"`);
              } else {
                console.log('No update needed, title is already up to date');
              }
            } else {
              console.log('Base branch does not start with "dev/", no update needed');
            }
          }

          updatePRTitle().catch(error => core.setFailed(error.message));
