name: Update PR Title

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  update_pr_title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Add labels based on PR title
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            require('./.github/workflows/pr-edit.js')({ github, context });