name: Update PR Title

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  update_pr_title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Execute script
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return require('./.github/workflows/pr-edit.mjs');
